source 'https://rubygems.org'

gem 'cucumber'
gem 'rspec'
gem 'rake'
gem 'page-object'
gem 'faker'
gem 'data_magic'
gem 'require_all'
gem 'activerecord'
gem 'factory_girl'
gem 'database_cleaner'
gem 'sqlite3'
gem 'nokogiri'
gem 'builder'
gem 'soap-object'
gem 'fig_newton'
gem 'pretty_face', '0.10.3', git: 'https://github.com/cheezy/pretty_face.git'